name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  csfixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: PHP CS Fixer
        run: |
          docker run --rm -v ${{ github.workspace }}:/app --user $(id -u):$(id -g) -w /app --entrypoint composer chialab/php:8.3 install
          docker run --rm -v ${{ github.workspace }}:/app --user $(id -u):$(id -g) -w /app --entrypoint /app/vendor/bin/php-cs-fixer chialab/php:8.3 check --config=.php-cs-fixer.dist.php
